version: "3.9"

networks:
  doro-net:
    driver: bridge

services:

  serviceregistry:
    image: deveshmodi662/serviceregistry-app:v3
    container_name: eureka
    ports:
      - "8761:8761"
    env_file:
      - serviceregistry/.envEureka
    networks:
      - doro-net

  gateway:
    image: deveshmodi662/gatewayservice-app:v3
    container_name: gateway
    ports:
      - "8765:8765"
    env_file:
      - gatewayservice/.envGateway
    depends_on:
      - serviceregistry
    networks:
      - doro-net

  dorobe:
    image: deveshmodi662/dorobe-app:v3
    container_name: dorobe
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - serviceregistry
    networks:
      - doro-net

  exportservice:
    image: deveshmodi662/exportservice-app:v3
    container_name: export
    ports:
      - "8080:8080"
    env_file:
      - .envExport
    depends_on:
      - serviceregistry
      - dorobe
    networks:
      - doro-net

  collabservice:
    image: deveshmodi662/collabservice-app:v3
    container_name: collab
    ports:
      - "8888:8888"
    env_file:
      - collabservice/.envWs
    depends_on:
      - serviceregistry
    networks:
      - doro-net

  ui:
    image: deveshmodi662/doroui-app:v3
    container_name: doroui
    ports:
      - "80:80"
    env_file:
      - doroui/.env
    depends_on:
      - gateway
    networks:
      - doro-net