apiVersion: v1
kind: Service
metadata:
  name: collab-service
spec:
  type: NodePort
  selector:
    app: doro
    microservice : collab
  ports:
    - nodePort: 30888
      port: 8888
      targetPort: 8888
      