apiVersion: v1
kind: Service
metadata:
  name: doroui-service
spec:
  type: NodePort
  selector:
    app: doro
    microservice : doroui
  ports:
    - nodePort: 30080
      port: 80
      targetPort: 80
      