apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: NodePort
  selector:
    app: doro
    microservice : gateway
  ports:
    - nodePort: 30765
      port: 8765
      targetPort: 8765
      