apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- collab-service.yaml
- dorobe-service.yaml
- doroui-service.yaml
- eureka-service.yaml
- export-service.yaml
- gateway-service.yaml